Feat : assignment2 ContactManager
Preethxsuresh/C_Sharp pull request #2
Opened 2023-08-18 09:57 UTC by Preethxsuresh

A Console-based contact manager application that allows to manage Contacts including View Contacts, Add New Contact, Search Contacts, Edit Contact and Delete Contact functionalities.

2023-08-23 09:05 UTC, nandhakumarsoliton requested changes
Please find the first set of review comments and make the changes wherever required.
Also please don't apply the comments only on the line where it is commented, Kindly make the comments reflected in all the applicable places.

2023-08-24 03:54 UTC, Preethxsuresh commented on src/assignmenttwo/Phone.cs
> +            return;
yes, return is not necessary there. I'll make sure to remove it.

2023-08-24 15:56 UTC, Preethxsuresh commented on src/assignmenttwo/Program.cs
> +            Thread.Sleep(1000);
I gave Console.Clear() at the beginning of the Menu() function so that each time the loop is called It erases the console. To display the welcome message from the main class for 1 second I created the delay. Now I removed it and added it along with invalid input. so that each time the user enters invalid input the console gets erased.

2023-08-29 06:44 UTC, nandhakumarsoliton requested changes

2023-08-29 06:44 UTC, nandhakumarsoliton commented on src/assignmenttwo/Contact.cs
> +        /// <param name="name">The name of the contactsList.</param>
```suggestion
        /// <param name="name">The name of the contact.</param>
```
I feel like this suggestion would help you.

2023-08-29 06:44 UTC, nandhakumarsoliton commented on src/assignmenttwo/Contact.cs
> +        /// Gets or sets the name of the contactsList.
This is not the name of the contactsList instead this is the name of the contact.
Please update these accordingly wherever required.
```suggestion
        /// Gets or sets the name of the contact.
```

2023-08-29 06:44 UTC, nandhakumarsoliton commented on src/assignmenttwo/Phone.cs
> +        private static string contactRegex = @"^\d{10}$";
Phone number is validated with only 10 digits.
These are also valid numbers right? +91 8976543209

2023-08-29 06:44 UTC, nandhakumarsoliton commented on src/assignmenttwo/Phone.cs
> +        private static List<Contact> contactsList = new ();
List<Contact> can be contacts right?

2023-08-29 06:44 UTC, nandhakumarsoliton commented on src/assignmenttwo/Phone.cs
> +                input = Console.ReadLine();
Can I have the Addition notes for my contact to be Empty?

2023-08-30 05:58 UTC, nandhakumarsoliton requested changes

2023-08-30 05:58 UTC, nandhakumarsoliton commented on src/assignmenttwo/Phone.cs
> +                    contacts = contacts.Where(n => n.Name.Contains(inputName, StringComparison.OrdinalIgnoreCase)).ToList();
I feel this might cause some functionality issues, Can you recheck this piece of code's working?

2023-08-30 09:34 UTC, merged